name: Release

on:
  push:
  pull_request:

jobs:
  build:
    name: Build wheel
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
    - name: Run bdist_wheel
      run: python setup.py bdist_wheel --universal
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheel
        path: dist/*.whl
  test:
    name: Run tests
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        flask-version: ["<2.3", ">=2.3"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install flask
      run: pip install "flask${{ matrix.flask-version }}"
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: wheel
    - name: Install wheel
      run: pip install dist/*.whl
    - name: Test
      run: pytest
  pypi-publish:
    name: Upload release to PyPI
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: wheel
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
